- ansible.builtin.import_role:
    name: compose_hull
  vars:
    service_defaults:
      name:  watchtower
      port: 8080
      traefik: false
      external: false
      watchtower: true
      autoheal: true
      # service-specific config
      version: latest
      poll_interval: 86400  # 24h
      http_token:           # disabled by default
      shoutrrr_url: smtp://m06f54d2:Mg6fGstEHTsBzWiNtZzP@v129687.kasserver.com:587/?from=nas@m-kirchner.de&to=martin@m-kirchner.de


